sklearn.preprocessing 是一个对数据预处理的包
 
preprocessing 这个工具 处理一列列数据 对数据做 归一化 等预处理操作

In [1]:
import sklearn.preprocessing as preprocessing

In [12]:
import numpy as np
import pandas as pd

In [18]:
X = np.array([ 1., -1.,  2., 2.,  0.,  0., 0.,  1., -1.])
X = pd.DataFrame(X.reshape(-1,1))
X = X[0]
X

0    1.0
1   -1.0
2    2.0
3    2.0
4    0.0
5    0.0
6    0.0
7    1.0
8   -1.0
Name: 0, dtype: float64

In [19]:
preprocessing.scale(X)

array([ 0.52128604, -1.35534369,  1.4596009 ,  1.4596009 , -0.41702883,
       -0.41702883, -0.41702883,  0.52128604, -1.35534369])

可以看出来这里preprocessing.scale 所需要的参数是一维的 

换句话说 对这一列上面的每一个数字做了归一化 是一列粒度的

到这里 其实上已经完成归一化的过程

但实际模型训练时 我们希望保持训练集 和 测试集 归一化粒度一致

就需要有一个函数能把训练集的参数 保存下来 就是 这里的StandardScaler()

In [20]:
scaler = preprocessing.StandardScaler()

In [21]:
age_scale_param = scaler.fit(X)

ValueError: Expected 2D array, got 1D array instead:
array=[ 1. -1.  2.  2.  0.  0.  0.  1. -1.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

可以看到 报错提示 传入的参数 类型不对 需要二维的参数

结合上面的例子 我们是一列一列的处理数据

现在X实际上是一个一维数组

reshape的意思 是 把数组 重新分行列 

(1, -1) 即 一行 [[1, 2, 4]]
(-1, 1) 即 一列 [[1], [2], [4]]

In [24]:
age_scale_param = scaler.fit(X.values.reshape(1, -1))
scaler.fit_transform(X.values.reshape(1, -1), age_scale_param)[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看到 如果把数组变成一行 那么输出的就是全零

In [26]:
age_scale_param = scaler.fit(X.values.reshape(-1, 1))
scaler.fit_transform(X.values.reshape(-1, 1), age_scale_param)

array([[ 0.52128604],
       [-1.35534369],
       [ 1.4596009 ],
       [ 1.4596009 ],
       [-0.41702883],
       [-0.41702883],
       [-0.41702883],
       [ 0.52128604],
       [-1.35534369]])

In [ ]:
如果把数据变成一列 就能得到我们想要的结果

In [ ]:
import sklearn.preprocessing as preprocessing
scaler = preprocessing.StandardScaler()
age_scale_param = scaler.fit(df['Age'].values.reshape(-1, 1))
df['Age_scaled'] = scaler.fit_transform(
    df['Age'].values.reshape(-1, 1), age_scale_param)
fare_scale_param = scaler.fit(df['Fare'].values.reshape(-1, 1))
df['Fare_scaled'] = scaler.fit_transform(
    df['Fare'].values.reshape(-1, 1), fare_scale_param)
df